databases:
  - name: frugal-pal
    databaseName: frugal_pal
    user: frugal_pal_user

services:
  - type: web
    name: frugal-pal
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: frugal-pal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false